/** Public comment/activity wire budgets are owned by collaboration-protocol. */
export {
  ACTIVITY_HEADLINE_MAX_LENGTH,
  ACTIVITY_LIST_PAGE_DEFAULT,
  ACTIVITY_LIST_PAGE_MAX,
  ACTIVITY_LIST_PAGE_MIN,
  ACTIVITY_SUBJECTS_MAX_COUNT,
  COMMENT_ATTACHMENT_ALLOWED_MEDIA_TYPES,
  COMMENT_ATTACHMENT_FILENAME_MAX_LENGTH,
  COMMENT_ATTACHMENT_FILENAME_MIN_LENGTH,
  COMMENT_ATTACHMENT_MAX_BYTES,
  COMMENT_ATTACHMENTS_MAX_COUNT,
  COMMENT_BODY_FORMAT,
  COMMENT_LIST_PAGE_DEFAULT,
  COMMENT_LIST_PAGE_MAX,
  COMMENT_LIST_PAGE_MIN,
  COMMENT_TOMBSTONE_REASON_MAX_LENGTH,
  HUMAN_COMMENT_BODY_MAX_LENGTH as COMMENT_BODY_MAX_LENGTH,
  HUMAN_COMMENT_BODY_MIN_LENGTH as COMMENT_BODY_MIN_LENGTH
} from "@planweave-ai/collaboration-protocol/core/limits";

/** Server-only staged upload lifecycle limits. */
export const COMMENT_STAGED_UPLOAD_TTL_MS = 3_600_000 as const;
export const COMMENT_STAGED_UPLOAD_MIN_TTL_MS = 60_000 as const;
export const COMMENT_STAGED_UPLOAD_MAX_TTL_MS = 86_400_000 as const;

/** Server-only retention and persistence revision policy. */
export const ACTIVITY_RETENTION_MAX_AGE_MS = 31_536_000_000 as const;
export const COMMENT_TOMBSTONE_RETENTION_INDEFINITE = true as const;
export const COMMENT_INITIAL_REVISION = 1 as const;
